# Generated by Django 3.2.6 on 2021-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroEnvioMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=15, verbose_name='Numero de Factura')),
                ('fecha_envio', models.DateTimeField(verbose_name='Fecha de Envio')),
                ('Estado', models.CharField(max_length=10, verbose_name='Estado')),
                ('archivo', models.CharField(max_length=100, verbose_name='Archivo')),
                ('ruta', models.CharField(max_length=300, null=True, verbose_name='Ruta')),
            ],
        ),
    ]
